---
- name: Install zsh
  package:
    name: zsh
    state: present

- name: Download oh-my-zsh installer
  get_url:
    url: https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh
    dest: "{{user_home}}"
    owner: "{{user}}"
    mode: 0700

- name: Run oh-my-zsh installer
  shell: "{{user_home}}/install.sh"
  become: "{{user}}"

- name: Configure user
  user:
    name: "{{user}}"
    shell: /bin/zsh
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa